SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/spatial/todb/hw3/Health_Facility_General_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "10/22/2023 
20:12:33.016604".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3125W  The character data in row "F0-1" and column "8" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F0-1" and column "9" was truncated 
because the data is longer than the target database column.

SQL3121W  The field value in row "F0-1" and column "11" cannot be converted to 
a FLOAT value.  A null was loaded.

SQL3121W  The field value in row "F0-1" and column "12" cannot be converted to 
a FLOAT value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3125W  The character data in row "F1-582" and column "2" was truncated 
because the data is longer than the target database column.

SQL3227W  Record token "F1-582" refers to user record number "2549".

SQL3110N  The utility has completed processing.  "6146" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "6146".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "10/22/2023 
20:12:33.104662".

SQL3500W  The utility is beginning the "BUILD" phase at time "10/22/2023 
20:12:33.109849".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "10/22/2023 
20:12:33.176040".

SQL3500W  The utility is beginning the "DELETE" phase at time "10/22/2023 
20:12:33.222445".

SQL3509W  The utility has deleted "190" rows from the table.

SQL3515W  The utility has finished the "DELETE" phase at time "10/22/2023 
20:12:33.246980".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 6146
Number of rows skipped      = 0
Number of rows loaded       = 6146
Number of rows rejected     = 0
Number of rows deleted      = 190
Number of rows committed    = 6146

SQL3501W  The table space(s) in which the table resides will not be placed in 
backup pending state since forward recovery is disabled for the database.

SQL3109N  The utility is beginning to load data from file 
"/home/spatial/todb/hw3/Health_Facility_Certification_Information.csv".

SQL3500W  The utility is beginning the "LOAD" phase at time "10/22/2023 
22:38:24.485254".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3121W  The field value in row "F0-1" and column "6" cannot be converted to 
a FLOAT value.  A null was loaded.

SQL3227W  Record token "F0-1" refers to user record number "1".

SQL3125W  The character data in row "F0-3244" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F0-3245" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F0-3246" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F0-3247" and column "2" was truncated 
because the data is longer than the target database column.

SQL3125W  The character data in row "F0-3248" and column "2" was truncated 
because the data is longer than the target database column.

SQL3227W  Record token "F0-3244" refers to user record number "15399".

SQL3227W  Record token "F0-3245" refers to user record number "15400".

SQL3227W  Record token "F0-3246" refers to user record number "15401".

SQL3227W  Record token "F0-3247" refers to user record number "15402".

SQL3227W  Record token "F0-3248" refers to user record number "15403".

SQL3110N  The utility has completed processing.  "47662" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "47662".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "10/22/2023 
22:38:24.605733".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 47662
Number of rows skipped      = 0
Number of rows loaded       = 47662
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 47662

